version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: auth_postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Aart_t4m3
      POSTGRES_DB: db_auth
    ports:
      - "50052:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  aut-service: #
      build: .  
      container_name: auth_service_container
      ports:
        - "50051:50051"
      environment:
        - DB_HOST=postgres_db
        - DB_USER=admin
        - DB_PASSWORD=Aart_t4m3
        - DB_NAME=db_auth
        - DB_PORT=5432
        - RABBITMQ_URL=amqp://guest:guest@[IP_ADDRESS]:5672/
      depends_on:
        - postgres_db # Önce veri tabanının başlamasını sağlar
      restart: always

volumes:
  pg_data:
    driver: local